export const seedQuestions = [
  {
    id: "comb-001",
    scope: "comb",
    chapter: "组合逻辑电路",
    title: "74HC138 低有效输出",
    type: "single_choice",
    text: "74HC138 的输出为低有效。若用它实现 F(A,B,C)=Σm(0,2,6)，且只允许外接一个门，应把 Y0、Y2、Y6 接到哪种门？",
    options: ["与门", "或门", "与非门", "或非门"],
    answer: 2,
    answerText: "与非门",
    explanation: "74HC138 被选中的最小项输出为 0。只要 Y0、Y2、Y6 中任意一个为 0，F 就应为 1，因此使用与非门最合适。",
    knowledge: ["译码器", "集成组合器件"],
    keywords: [],
    difficulty: 2
  },
  {
    id: "comb-002",
    scope: "comb",
    chapter: "组合逻辑电路",
    title: "数据选择器实现函数",
    type: "single_choice",
    text: "用 4 选 1 数据选择器实现 F(A,B,C)=Σm(1,2,6,7)，令选择端 S1S0=AB。数据输入 D0、D1、D2、D3 应分别接什么？",
    options: ["C、C'、0、1", "C'、C、0、1", "0、1、C、C'", "1、0、C'、C"],
    answer: 0,
    answerText: "C、C'、0、1",
    explanation: "按 AB 分组：00 时 F=C，01 时 F=C'，10 时 F=0，11 时 F=1。",
    knowledge: ["数据选择器", "函数实现"],
    keywords: [],
    difficulty: 2
  },
  {
    id: "comb-003",
    scope: "comb",
    chapter: "组合逻辑电路",
    title: "两位数值比较器",
    type: "single_choice",
    text: "两位二进制数 A=A1A0，B=B1B0。表示 A>B 的逻辑条件最准确的是哪一个？",
    options: ["A1B1' + (A1 同或 B1)A0B0'", "A0B0' + A1B1", "A1B1 + A0B0", "(A1+A0)(B1'+B0')"],
    answer: 0,
    answerText: "A1B1' + (A1 同或 B1)A0B0'",
    explanation: "比较时先看高位；高位相等时，再比较低位。",
    knowledge: ["比较器", "组合逻辑设计"],
    keywords: [],
    difficulty: 3
  },
  {
    id: "comb-004",
    scope: "comb",
    chapter: "组合逻辑电路",
    title: "静态 1 冒险",
    type: "single_choice",
    text: "某与或式在两个相邻最小项之间切换时，理论输出应保持 1，但实际可能出现短暂 0 脉冲。这种现象称为？",
    options: ["静态 0 冒险", "静态 1 冒险", "动态冒险", "亚稳态"],
    answer: 1,
    answerText: "静态 1 冒险",
    explanation: "输出本应稳定为 1，却因路径延迟短暂跌到 0，这是静态 1 冒险。",
    knowledge: ["竞争冒险", "卡诺图覆盖"],
    keywords: [],
    difficulty: 3
  },
  {
    id: "comb-005",
    scope: "comb",
    chapter: "组合逻辑电路",
    title: "比较器设计简答",
    type: "analysis",
    text: "设计一个两位二进制比较器的输出 F，使 A=A1A0 大于 B=B1B0 时 F=1。请写出逻辑表达式，并说明比较顺序。",
    options: [],
    answerText: "F = A1B1' + (A1 同或 B1)A0B0'。先比较高位，高位相等时再比较低位。",
    explanation: "A1=1 且 B1=0 时 A 一定大；高位相等时再看低位。",
    knowledge: ["比较器", "组合逻辑设计"],
    keywords: ["A1B1'", "同或", "A0B0'", "高位", "低位"],
    difficulty: 3
  },
  {
    id: "ff-001",
    scope: "ff",
    chapter: "集成触发器",
    title: "T 触发器构成",
    type: "single_choice",
    text: "用 JK 触发器构成 T 触发器，最直接的连接方式是？",
    options: ["J=T，K=0", "J=0，K=T", "J=T，K=T", "J=T，K=T'"],
    answer: 2,
    answerText: "J=T，K=T",
    explanation: "JK 触发器在 J=K=0 时保持，在 J=K=1 时翻转，所以令 J=K=T。",
    knowledge: ["JK 触发器", "T 触发器"],
    keywords: [],
    difficulty: 2
  },
  {
    id: "ff-002",
    scope: "ff",
    chapter: "集成触发器",
    title: "建立时间",
    type: "single_choice",
    text: "触发器的数据输入必须在有效时钟沿到来前保持稳定一段最小时间，这个时间称为？",
    options: ["传输延迟", "保持时间", "建立时间", "恢复时间"],
    answer: 2,
    answerText: "建立时间",
    explanation: "有效时钟沿到来之前，数据需要提前稳定的最小时间是建立时间。",
    knowledge: ["建立保持时间", "时序约束"],
    keywords: [],
    difficulty: 2
  },
  {
    id: "ff-003",
    scope: "ff",
    chapter: "集成触发器",
    title: "JK 触发器状态序列",
    type: "single_choice",
    text: "JK 触发器初态 Q=0。连续三个有效时钟沿对应输入分别为 10、11、01。第三个时钟沿后 Q 为？",
    options: ["0", "1", "翻转两次后不确定", "取决于时钟脉宽"],
    answer: 0,
    answerText: "0",
    explanation: "第一次置 1；第二次翻转为 0；第三次仍置 0。",
    knowledge: ["JK 触发器", "状态推演"],
    keywords: [],
    difficulty: 3
  },
  {
    id: "ff-004",
    scope: "ff",
    chapter: "集成触发器",
    title: "触发器转换说明",
    type: "analysis",
    text: "请说明如何用 JK 触发器实现 D 触发器功能，并解释为什么这样连接可以得到 Q(n+1)=D。",
    options: [],
    answerText: "令 J=D，K=D'。当 D=1 时置 1；当 D=0 时置 0，所以次态等于 D。",
    explanation: "把 D 和 D' 分别接到 J、K，就能让输出在有效时钟沿后等于 D。",
    knowledge: ["触发器转换", "JK 触发器", "D 触发器"],
    keywords: ["J=D", "K=D'", "置1", "置0"],
    difficulty: 3
  },
  {
    id: "ff-005",
    scope: "ff",
    chapter: "集成触发器",
    title: "脉冲触发 SR 触发器波形",
    type: "waveform_analysis",
    text: "脉冲触发 SR 触发器初始状态 Q=0。四个 CLK 脉冲期间 SR 依次为 10、00、01、10。请写出每次脉冲后的 Q 状态。",
    options: [],
    answerText: "Q 序列为 1、1、0、1。",
    explanation: "依次执行置 1、保持、清 0、置 1。",
    knowledge: ["SR 触发器", "波形分析", "脉冲触发"],
    keywords: ["1、1、0、1", "置1", "保持", "清0"],
    difficulty: 3
  }
].map((question) => ({
  imported: false,
  source: "平台内置题库",
  ...question
}));
