export const seedQuestions = [
  {
    id: "base-001",
    scope: "basic-logic",
    chapter: "基础逻辑",
    title: "二进制与十进制转换",
    type: "single_choice",
    text: "二进制数 101101 转换为十进制数是多少？",
    options: ["43", "45", "47", "53"],
    answer: 1,
    answerText: "45",
    explanation: "101101B = 32 + 8 + 4 + 1 = 45。",
    knowledge: ["数制与编码", "二进制转换"],
    keywords: [],
    difficulty: 1
  },
  {
    id: "base-002",
    scope: "basic-logic",
    chapter: "基础逻辑",
    title: "十六进制转换",
    type: "single_choice",
    text: "十六进制数 2F 转换为十进制数是多少？",
    options: ["31", "41", "47", "52"],
    answer: 2,
    answerText: "47",
    explanation: "2F(H)=2×16+15=47。",
    knowledge: ["数制与编码", "十六进制转换"],
    keywords: [],
    difficulty: 1
  },
  {
    id: "base-003",
    scope: "basic-logic",
    chapter: "基础逻辑",
    title: "8421 BCD 编码",
    type: "single_choice",
    text: "十进制数 59 的 8421 BCD 编码是哪个？",
    options: ["0101 1001", "0101 1011", "0110 1001", "0100 1001"],
    answer: 0,
    answerText: "0101 1001",
    explanation: "8421 BCD 是逐位编码：5 为 0101，9 为 1001。",
    knowledge: ["数制与编码", "BCD 编码"],
    keywords: [],
    difficulty: 1
  },
  {
    id: "base-004",
    scope: "basic-logic",
    chapter: "基础逻辑",
    title: "格雷码特点",
    type: "single_choice",
    text: "格雷码相邻两个编码之间通常只有几位不同？",
    options: ["1 位", "2 位", "3 位", "不固定"],
    answer: 0,
    answerText: "1 位",
    explanation: "格雷码的核心特点是相邻编码只有一位发生变化，可减少状态切换误读。",
    knowledge: ["数制与编码", "格雷码"],
    keywords: [],
    difficulty: 1
  },
  {
    id: "base-005",
    scope: "basic-logic",
    chapter: "基础逻辑",
    title: "逻辑门输出判断",
    type: "single_choice",
    text: "输入 A=1、B=0 时，表达式 Y=(A+B)' 的输出是多少？",
    options: ["0", "1", "A", "B"],
    answer: 0,
    answerText: "0",
    explanation: "A+B=1，取反后 Y=0。",
    knowledge: ["逻辑门", "或非门"],
    keywords: [],
    difficulty: 1
  },
  {
    id: "base-006",
    scope: "basic-logic",
    chapter: "基础逻辑",
    title: "异或门功能",
    type: "single_choice",
    text: "异或门 A⊕B 在什么情况下输出 1？",
    options: ["A、B 都为 0", "A、B 都为 1", "A、B 不同", "A、B 相同"],
    answer: 2,
    answerText: "A、B 不同",
    explanation: "异或门表示不相同检测，两个输入不同则输出 1。",
    knowledge: ["逻辑门", "异或门"],
    keywords: [],
    difficulty: 1
  },
  {
    id: "base-007",
    scope: "basic-logic",
    chapter: "基础逻辑",
    title: "德摩根定律",
    type: "single_choice",
    text: "根据德摩根定律，(AB)' 等价于哪一个表达式？",
    options: ["A'B'", "A'+B'", "A+B", "(A+B)'"],
    answer: 1,
    answerText: "A'+B'",
    explanation: "乘积取反等于各变量取反后相加，即 (AB)'=A'+B'。",
    knowledge: ["逻辑代数", "德摩根定律"],
    keywords: [],
    difficulty: 1
  },
  {
    id: "base-008",
    scope: "basic-logic",
    chapter: "基础逻辑",
    title: "吸收律化简",
    type: "single_choice",
    text: "逻辑表达式 A+AB 可化简为哪一个？",
    options: ["A", "B", "AB", "A+B"],
    answer: 0,
    answerText: "A",
    explanation: "根据吸收律 A+AB=A。",
    knowledge: ["逻辑代数", "逻辑函数化简"],
    keywords: [],
    difficulty: 1
  },
  {
    id: "base-009",
    scope: "basic-logic",
    chapter: "基础逻辑",
    title: "真值表最小项",
    type: "single_choice",
    text: "三变量函数 F(A,B,C)=Σm(1,3,7)，当 ABC=101 时，F 的值是多少？",
    options: ["0", "1", "不确定", "取决于无关项"],
    answer: 0,
    answerText: "0",
    explanation: "ABC=101 对应最小项 m5，m5 不在给定集合中，所以 F=0。",
    knowledge: ["真值表", "最小项"],
    keywords: [],
    difficulty: 2
  },
  {
    id: "base-010",
    scope: "basic-logic",
    chapter: "基础逻辑",
    title: "逻辑函数化简",
    type: "single_choice",
    text: "逻辑函数 F=AB+AB' 可化简为哪一个？",
    options: ["A", "B", "A+B", "AB"],
    answer: 0,
    answerText: "A",
    explanation: "AB+AB'=A(B+B')=A。",
    knowledge: ["逻辑函数化简", "逻辑代数"],
    keywords: [],
    difficulty: 1
  },
  {
    id: "base-011",
    scope: "basic-logic",
    chapter: "基础逻辑",
    title: "卡诺图相邻项合并",
    type: "single_choice",
    text: "在三变量卡诺图中，相邻两个 1 格合并后通常可以消去几个变量？",
    options: ["0 个", "1 个", "2 个", "3 个"],
    answer: 1,
    answerText: "1 个",
    explanation: "两个相邻最小项只有一个变量不同，合并后消去这个变化变量。",
    knowledge: ["逻辑函数化简", "卡诺图"],
    keywords: [],
    difficulty: 2
  },
  {
    id: "base-012",
    scope: "basic-logic",
    chapter: "基础逻辑",
    title: "由真值表写表达式",
    type: "analysis",
    text: "某二变量函数 F 在 AB=01、10、11 时为 1，在 AB=00 时为 0。请写出 F 的最简表达式，并说明它对应哪种基本逻辑门。",
    options: [],
    answerText: "F=A+B，对应或门。",
    explanation: "只要 A 或 B 中至少一个为 1，F 就为 1；仅 00 时为 0，所以 F=A+B。",
    knowledge: ["真值表", "逻辑门", "逻辑函数化简"],
    keywords: ["A+B", "或门"],
    difficulty: 2
  },
  {
    id: "comb-001",
    scope: "combinational",
    chapter: "组合逻辑",
    title: "编码器输出",
    type: "single_choice",
    text: "8 线-3 线普通编码器中，若输入 I5 有效，输出二进制编码通常是多少？",
    options: ["101", "100", "011", "110"],
    answer: 0,
    answerText: "101",
    explanation: "输入编号 5 的二进制编码为 101。",
    knowledge: ["编码器", "组合逻辑"],
    keywords: [],
    difficulty: 1
  },
  {
    id: "comb-002",
    scope: "combinational",
    chapter: "组合逻辑",
    title: "优先编码器",
    type: "single_choice",
    text: "优先编码器中若 I7 和 I3 同时有效，且 I7 优先级更高，输出应对应哪一路？",
    options: ["I3", "I7", "I4", "无效"],
    answer: 1,
    answerText: "I7",
    explanation: "优先编码器会输出最高优先级有效输入的编码。",
    knowledge: ["编码器", "优先编码器"],
    keywords: [],
    difficulty: 2
  },
  {
    id: "comb-003",
    scope: "combinational",
    chapter: "组合逻辑",
    title: "3-8 译码器输出",
    type: "single_choice",
    text: "高电平有效的 3-8 译码器输入 ABC=110 时，哪一路输出为 1？",
    options: ["Y5", "Y6", "Y7", "Y3"],
    answer: 1,
    answerText: "Y6",
    explanation: "ABC=110 对应十进制 6，所以 Y6 有效。",
    knowledge: ["译码器", "组合逻辑"],
    keywords: [],
    difficulty: 1
  },
  {
    id: "comb-004",
    scope: "combinational",
    chapter: "组合逻辑",
    title: "译码器实现函数",
    type: "single_choice",
    text: "用高电平有效 3-8 译码器实现 F(A,B,C)=Σm(0,2,6)，应如何连接输出？",
    options: ["Y0、Y2、Y6 接与门", "Y0、Y2、Y6 接或门", "Y0、Y2、Y6 接异或门", "只接 Y6"],
    answer: 1,
    answerText: "Y0、Y2、Y6 接或门",
    explanation: "高电平有效译码器中，对应最小项输出为 1，将目标最小项或起来即可得到 F。",
    knowledge: ["译码器", "逻辑函数实现"],
    keywords: [],
    difficulty: 2
  },
  {
    id: "comb-005",
    scope: "combinational",
    chapter: "组合逻辑",
    title: "数据选择器",
    type: "single_choice",
    text: "4 选 1 数据选择器中，选择端 S1S0=10 时，输出通常等于哪一路数据输入？",
    options: ["D0", "D1", "D2", "D3"],
    answer: 2,
    answerText: "D2",
    explanation: "选择端二进制 10 表示十进制 2，因此选择 D2。",
    knowledge: ["数据选择器", "组合逻辑"],
    keywords: [],
    difficulty: 1
  },
  {
    id: "comb-006",
    scope: "combinational",
    chapter: "组合逻辑",
    title: "数据选择器实现函数",
    type: "single_choice",
    text: "用 4 选 1 数据选择器实现 F(A,B,C)=Σm(1,2,6,7)，令选择端 S1S0=AB。D0、D1、D2、D3 应分别接什么？",
    options: ["C、C'、0、1", "C'、C、0、1", "0、1、C、C'", "1、0、C'、C"],
    answer: 0,
    answerText: "C、C'、0、1",
    explanation: "按 AB 分组：00 时 F=C，01 时 F=C'，10 时 F=0，11 时 F=1。",
    knowledge: ["数据选择器", "逻辑函数实现"],
    keywords: [],
    difficulty: 2
  },
  {
    id: "comb-007",
    scope: "combinational",
    chapter: "组合逻辑",
    title: "半加器",
    type: "single_choice",
    text: "半加器的两个输入为 A、B，则和位 S 与进位 C 分别为哪一组？",
    options: ["S=A+B，C=AB", "S=A⊕B，C=AB", "S=AB，C=A⊕B", "S=A⊙B，C=A+B"],
    answer: 1,
    answerText: "S=A⊕B，C=AB",
    explanation: "半加器和位是异或，进位是与。",
    knowledge: ["加法器", "半加器"],
    keywords: [],
    difficulty: 1
  },
  {
    id: "comb-008",
    scope: "combinational",
    chapter: "组合逻辑",
    title: "全加器进位",
    type: "single_choice",
    text: "全加器输入 A=1、B=1、Cin=0 时，输出 S 和 Cout 分别为多少？",
    options: ["S=0，Cout=1", "S=1，Cout=0", "S=1，Cout=1", "S=0，Cout=0"],
    answer: 0,
    answerText: "S=0，Cout=1",
    explanation: "1+1+0=10B，因此和位为 0，进位为 1。",
    knowledge: ["加法器", "全加器"],
    keywords: [],
    difficulty: 1
  },
  {
    id: "comb-009",
    scope: "combinational",
    chapter: "组合逻辑",
    title: "全加器表达式",
    type: "single_choice",
    text: "全加器和位 S 的表达式是哪一个？",
    options: ["A⊕B⊕Cin", "AB+Cin", "A+B+Cin", "ABCin"],
    answer: 0,
    answerText: "A⊕B⊕Cin",
    explanation: "全加器和位为三个输入的异或。",
    knowledge: ["加法器", "全加器"],
    keywords: [],
    difficulty: 2
  },
  {
    id: "comb-010",
    scope: "combinational",
    chapter: "组合逻辑",
    title: "两位比较器",
    type: "single_choice",
    text: "两位二进制数 A=A1A0、B=B1B0。表示 A>B 的逻辑条件最准确的是哪一个？",
    options: ["A1B1' + (A1⊙B1)A0B0'", "A0B0' + A1B1", "A1B1 + A0B0", "(A1+A0)(B1'+B0')"],
    answer: 0,
    answerText: "A1B1' + (A1⊙B1)A0B0'",
    explanation: "比较器先比较高位；高位相等时，再比较低位。",
    knowledge: ["比较器", "组合逻辑设计"],
    keywords: [],
    difficulty: 3
  },
  {
    id: "comb-011",
    scope: "combinational",
    chapter: "组合逻辑",
    title: "组合逻辑竞争冒险",
    type: "single_choice",
    text: "某与或式在两个相邻最小项之间切换时，理论输出应保持 1，但实际可能出现短暂 0 脉冲。这种现象称为？",
    options: ["静态 0 冒险", "静态 1 冒险", "动态冒险", "亚稳态"],
    answer: 1,
    answerText: "静态 1 冒险",
    explanation: "输出本应稳定为 1，却因不同路径延迟短暂跌到 0，这是静态 1 冒险。",
    knowledge: ["组合逻辑设计", "竞争冒险"],
    keywords: [],
    difficulty: 3
  },
  {
    id: "comb-012",
    scope: "combinational",
    chapter: "组合逻辑",
    title: "组合逻辑设计步骤",
    type: "analysis",
    text: "请简述设计一个组合逻辑电路的一般步骤，并举例说明它可用于编码器、译码器、数据选择器、加法器或比较器。",
    options: [],
    answerText: "一般步骤为：明确输入输出变量，列真值表，写出逻辑表达式，化简表达式，选择门电路或集成器件实现，最后验证功能。可用于全加器、译码器、比较器等组合逻辑设计。",
    explanation: "组合逻辑电路没有记忆功能，输出只由当前输入决定，因此真值表和逻辑函数化简是核心步骤。",
    knowledge: ["组合逻辑设计", "编码器", "译码器", "数据选择器", "加法器", "比较器"],
    keywords: ["真值表", "化简", "实现", "验证"],
    difficulty: 2
  },
  {
    id: "seq-001",
    scope: "sequential",
    chapter: "时序逻辑",
    title: "SR 触发器状态",
    type: "single_choice",
    text: "基本 SR 触发器在 S=0、R=0 时，通常处于什么状态？",
    options: ["置 1", "置 0", "保持", "禁止"],
    answer: 2,
    answerText: "保持",
    explanation: "S 和 R 均无效时，SR 触发器保持原状态。",
    knowledge: ["触发器", "SR 触发器"],
    keywords: [],
    difficulty: 1
  },
  {
    id: "seq-002",
    scope: "sequential",
    chapter: "时序逻辑",
    title: "D 触发器功能",
    type: "single_choice",
    text: "边沿触发 D 触发器在有效时钟沿到来后，Q(n+1) 等于什么？",
    options: ["0", "1", "D", "Q(n)'"],
    answer: 2,
    answerText: "D",
    explanation: "D 触发器在有效时钟沿采样 D，并把该值送到输出 Q。",
    knowledge: ["触发器", "D 触发器"],
    keywords: [],
    difficulty: 1
  },
  {
    id: "seq-003",
    scope: "sequential",
    chapter: "时序逻辑",
    title: "JK 触发器翻转",
    type: "single_choice",
    text: "JK 触发器在 J=1、K=1 且有效时钟沿到来时，输出将如何变化？",
    options: ["置 1", "置 0", "保持", "翻转"],
    answer: 3,
    answerText: "翻转",
    explanation: "JK 触发器在 J=K=1 时执行翻转功能。",
    knowledge: ["触发器", "JK 触发器"],
    keywords: [],
    difficulty: 1
  },
  {
    id: "seq-004",
    scope: "sequential",
    chapter: "时序逻辑",
    title: "T 触发器构成",
    type: "single_choice",
    text: "用 JK 触发器构成 T 触发器，最直接的连接方式是？",
    options: ["J=T，K=0", "J=0，K=T", "J=T，K=T", "J=T，K=T'"],
    answer: 2,
    answerText: "J=T，K=T",
    explanation: "JK 触发器在 J=K=0 时保持，在 J=K=1 时翻转，所以令 J=K=T。",
    knowledge: ["触发器", "JK 触发器", "T 触发器"],
    keywords: [],
    difficulty: 2
  },
  {
    id: "seq-005",
    scope: "sequential",
    chapter: "时序逻辑",
    title: "寄存器功能",
    type: "single_choice",
    text: "4 位寄存器通常需要几个 D 触发器来存放 4 位二进制数据？",
    options: ["1 个", "2 个", "4 个", "8 个"],
    answer: 2,
    answerText: "4 个",
    explanation: "每个 D 触发器存放 1 位数据，4 位数据需要 4 个触发器。",
    knowledge: ["寄存器", "D 触发器"],
    keywords: [],
    difficulty: 1
  },
  {
    id: "seq-006",
    scope: "sequential",
    chapter: "时序逻辑",
    title: "移位寄存器",
    type: "single_choice",
    text: "串入串出移位寄存器每来一个时钟脉冲通常完成什么操作？",
    options: ["所有位清零", "数据整体移动一位", "立即完成并行装载", "输出保持不变"],
    answer: 1,
    answerText: "数据整体移动一位",
    explanation: "移位寄存器在时钟作用下把数据按设定方向逐位移动。",
    knowledge: ["寄存器", "移位寄存器"],
    keywords: [],
    difficulty: 1
  },
  {
    id: "seq-007",
    scope: "sequential",
    chapter: "时序逻辑",
    title: "二进制计数器",
    type: "single_choice",
    text: "3 位二进制加法计数器最多可以表示多少个不同状态？",
    options: ["3 个", "6 个", "8 个", "16 个"],
    answer: 2,
    answerText: "8 个",
    explanation: "n 位二进制计数器最多有 2^n 个状态，3 位为 8 个。",
    knowledge: ["计数器", "二进制计数器"],
    keywords: [],
    difficulty: 1
  },
  {
    id: "seq-008",
    scope: "sequential",
    chapter: "时序逻辑",
    title: "模计数器",
    type: "single_choice",
    text: "模 10 计数器完成一轮计数需要多少个有效计数状态？",
    options: ["8 个", "9 个", "10 个", "16 个"],
    answer: 2,
    answerText: "10 个",
    explanation: "模 N 计数器有 N 个有效状态，因此模 10 有 10 个有效状态。",
    knowledge: ["计数器", "模计数器"],
    keywords: [],
    difficulty: 1
  },
  {
    id: "seq-009",
    scope: "sequential",
    chapter: "时序逻辑",
    title: "同步与异步计数器",
    type: "single_choice",
    text: "同步计数器与异步计数器的主要区别是什么？",
    options: ["是否使用触发器", "触发器是否共用同一个时钟", "是否有输出", "是否能计数"],
    answer: 1,
    answerText: "触发器是否共用同一个时钟",
    explanation: "同步计数器各触发器由同一时钟触发；异步计数器时钟逐级传递。",
    knowledge: ["计数器", "同步计数器", "异步计数器"],
    keywords: [],
    difficulty: 2
  },
  {
    id: "seq-010",
    scope: "sequential",
    chapter: "时序逻辑",
    title: "状态分析",
    type: "single_choice",
    text: "时序电路状态分析中，状态转移表主要描述什么？",
    options: ["当前状态、输入与次态/输出的关系", "电源电压大小", "导线长度", "元件封装"],
    answer: 0,
    answerText: "当前状态、输入与次态/输出的关系",
    explanation: "状态转移表用于描述当前状态和输入如何决定次态以及输出。",
    knowledge: ["状态分析", "状态转移表"],
    keywords: [],
    difficulty: 2
  },
  {
    id: "seq-011",
    scope: "sequential",
    chapter: "时序逻辑",
    title: "JK 触发器状态推演",
    type: "single_choice",
    text: "JK 触发器初态 Q=0。连续三个有效时钟沿对应输入分别为 10、11、01。第三个时钟沿后 Q 为？",
    options: ["0", "1", "翻转两次后不确定", "取决于时钟脉宽"],
    answer: 0,
    answerText: "0",
    explanation: "第一次置 1；第二次翻转为 0；第三次复位为 0。",
    knowledge: ["触发器", "状态分析", "JK 触发器"],
    keywords: [],
    difficulty: 3
  },
  {
    id: "seq-012",
    scope: "sequential",
    chapter: "时序逻辑",
    title: "波形分析",
    type: "analysis",
    text: "D 触发器初态 Q=0。在三个连续上升沿到来前，D 依次稳定为 1、0、1。请写出每个上升沿后的 Q 序列。",
    options: [],
    answerText: "Q 序列为 1、0、1。",
    explanation: "D 触发器在每个有效上升沿采样当时的 D 值，因此输出序列与 D 序列一致。",
    knowledge: ["波形分析", "D 触发器", "状态分析"],
    keywords: ["1、0、1", "上升沿", "采样", "D"],
    difficulty: 2
  }
].map((question) => ({
  imported: false,
  source: "平台内置题库",
  ...question
}));
