export const seedQuestions = [
  {
    id: "base-001",
    scope: "basic-logic",
    chapter: "基础逻辑",
    title: "二进制与十进制转换",
    type: "single_choice",
    text: "二进制数 101101 转换为十进制数是多少？",
    options: ["43", "45", "47", "53"],
    answer: 1,
    answerText: "45",
    explanation: "101101B = 32 + 8 + 4 + 1 = 45。",
    knowledge: ["数制与编码", "二进制转换"],
    keywords: [],
    difficulty: 1
  },
  {
    id: "base-002",
    scope: "basic-logic",
    chapter: "基础逻辑",
    title: "8421 BCD 编码",
    type: "single_choice",
    text: "十进制数 59 的 8421 BCD 编码是哪个？",
    options: ["0101 1001", "0101 1011", "0110 1001", "0100 1001"],
    answer: 0,
    answerText: "0101 1001",
    explanation: "8421 BCD 是逐位编码：5 为 0101，9 为 1001。",
    knowledge: ["数制与编码", "BCD 编码"],
    keywords: [],
    difficulty: 1
  },
  {
    id: "base-003",
    scope: "basic-logic",
    chapter: "基础逻辑",
    title: "逻辑门输出判断",
    type: "single_choice",
    text: "输入 A=1、B=0 时，表达式 Y=(A+B)' 的输出是多少？",
    options: ["0", "1", "A", "B"],
    answer: 0,
    answerText: "0",
    explanation: "A+B=1，取反后 Y=0。",
    knowledge: ["逻辑门", "或非门"],
    keywords: [],
    difficulty: 1
  },
  {
    id: "base-004",
    scope: "basic-logic",
    chapter: "基础逻辑",
    title: "德摩根定律",
    type: "single_choice",
    text: "根据德摩根定律，(AB)' 等价于哪一个表达式？",
    options: ["A'B'", "A'+B'", "A+B", "(A+B)'"],
    answer: 1,
    answerText: "A'+B'",
    explanation: "乘积取反等于各变量取反后相加，即 (AB)'=A'+B'。",
    knowledge: ["逻辑代数", "德摩根定律"],
    keywords: [],
    difficulty: 1
  },
  {
    id: "base-005",
    scope: "basic-logic",
    chapter: "基础逻辑",
    title: "真值表最小项",
    type: "single_choice",
    text: "三变量函数 F(A,B,C)=Σm(1,3,7)，当 ABC=101 时，F 的值是多少？",
    options: ["0", "1", "不确定", "取决于无关项"],
    answer: 0,
    answerText: "0",
    explanation: "ABC=101 对应最小项 m5，m5 不在给定集合中，所以 F=0。",
    knowledge: ["真值表", "最小项"],
    keywords: [],
    difficulty: 2
  },
  {
    id: "base-006",
    scope: "basic-logic",
    chapter: "基础逻辑",
    title: "逻辑函数化简",
    type: "single_choice",
    text: "逻辑函数 F=AB+AB' 可化简为哪一个？",
    options: ["A", "B", "A+B", "AB"],
    answer: 0,
    answerText: "A",
    explanation: "AB+AB'=A(B+B')=A。",
    knowledge: ["逻辑函数化简", "逻辑代数"],
    keywords: [],
    difficulty: 1
  },
  {
    id: "base-007",
    scope: "basic-logic",
    chapter: "基础逻辑",
    title: "卡诺图相邻项合并",
    type: "single_choice",
    text: "在三变量卡诺图中，相邻两个 1 格合并后通常可以消去几个变量？",
    options: ["0 个", "1 个", "2 个", "3 个"],
    answer: 1,
    answerText: "1 个",
    explanation: "两个相邻最小项只有一个变量不同，合并后消去这个变化变量。",
    knowledge: ["逻辑函数化简", "卡诺图"],
    keywords: [],
    difficulty: 2
  },
  {
    id: "base-008",
    scope: "basic-logic",
    chapter: "基础逻辑",
    title: "由真值表写表达式",
    type: "analysis",
    text: "某二变量函数 F 在 AB=01、10、11 时为 1，在 AB=00 时为 0。请写出 F 的最简表达式，并说明它对应哪种基本逻辑门。",
    options: [],
    answerText: "F=A+B，对应或门。",
    explanation: "只要 A 或 B 中至少一个为 1，F 就为 1；仅 00 时为 0，所以 F=A+B。",
    knowledge: ["真值表", "逻辑门", "逻辑函数化简"],
    keywords: ["A+B", "或门"],
    difficulty: 2
  },
  {
    id: "comb-001",
    scope: "combinational",
    chapter: "组合逻辑",
    title: "编码器输出",
    type: "single_choice",
    text: "8 线-3 线普通编码器中，若输入 I5 有效，输出二进制编码通常是多少？",
    options: ["101", "100", "011", "110"],
    answer: 0,
    answerText: "101",
    explanation: "输入编号 5 的二进制编码为 101。",
    knowledge: ["编码器", "组合逻辑"],
    keywords: [],
    difficulty: 1
  },
  {
    id: "comb-002",
    scope: "combinational",
    chapter: "组合逻辑",
    title: "3-8 译码器输出",
    type: "single_choice",
    text: "高电平有效的 3-8 译码器输入 ABC=110 时，哪一路输出为 1？",
    options: ["Y5", "Y6", "Y7", "Y3"],
    answer: 1,
    answerText: "Y6",
    explanation: "ABC=110 对应十进制 6，所以 Y6 有效。",
    knowledge: ["译码器", "组合逻辑"],
    keywords: [],
    difficulty: 1
  },
  {
    id: "comb-003",
    scope: "combinational",
    chapter: "组合逻辑",
    title: "数据选择器",
    type: "single_choice",
    text: "4 选 1 数据选择器中，选择端 S1S0=10 时，输出通常等于哪一路数据输入？",
    options: ["D0", "D1", "D2", "D3"],
    answer: 2,
    answerText: "D2",
    explanation: "选择端二进制 10 表示十进制 2，因此选择 D2。",
    knowledge: ["数据选择器", "组合逻辑"],
    keywords: [],
    difficulty: 1
  },
  {
    id: "comb-004",
    scope: "combinational",
    chapter: "组合逻辑",
    title: "半加器",
    type: "single_choice",
    text: "半加器的两个输入为 A、B，则和位 S 与进位 C 分别为哪一组？",
    options: ["S=A+B，C=AB", "S=A⊕B，C=AB", "S=AB，C=A⊕B", "S=A⊙B，C=A+B"],
    answer: 1,
    answerText: "S=A⊕B，C=AB",
    explanation: "半加器和位是异或，进位是与。",
    knowledge: ["加法器", "半加器"],
    keywords: [],
    difficulty: 1
  },
  {
    id: "comb-005",
    scope: "combinational",
    chapter: "组合逻辑",
    title: "全加器进位",
    type: "single_choice",
    text: "全加器输入 A=1、B=1、Cin=0 时，输出 S 和 Cout 分别为多少？",
    options: ["S=0，Cout=1", "S=1，Cout=0", "S=1，Cout=1", "S=0，Cout=0"],
    answer: 0,
    answerText: "S=0，Cout=1",
    explanation: "1+1+0=10B，因此和位为 0，进位为 1。",
    knowledge: ["加法器", "全加器"],
    keywords: [],
    difficulty: 1
  },
  {
    id: "comb-006",
    scope: "combinational",
    chapter: "组合逻辑",
    title: "两位比较器",
    type: "single_choice",
    text: "两位二进制数 A=A1A0、B=B1B0。表示 A>B 的逻辑条件最准确的是哪一个？",
    options: ["A1B1' + (A1⊙B1)A0B0'", "A0B0' + A1B1", "A1B1 + A0B0", "(A1+A0)(B1'+B0')"],
    answer: 0,
    answerText: "A1B1' + (A1⊙B1)A0B0'",
    explanation: "比较器先比较高位；高位相等时，再比较低位。",
    knowledge: ["比较器", "组合逻辑设计"],
    keywords: [],
    difficulty: 3
  },
  {
    id: "comb-007",
    scope: "combinational",
    chapter: "组合逻辑",
    title: "译码器实现函数",
    type: "single_choice",
    text: "用高电平有效 3-8 译码器实现 F(A,B,C)=Σm(0,2,6)，应如何连接输出？",
    options: ["Y0、Y2、Y6 接与门", "Y0、Y2、Y6 接或门", "Y0、Y2、Y6 接异或门", "只接 Y6"],
    answer: 1,
    answerText: "Y0、Y2、Y6 接或门",
    explanation: "高电平有效译码器中，对应最小项输出为 1，将目标最小项或起来即可得到 F。",
    knowledge: ["译码器", "逻辑函数实现"],
    keywords: [],
    difficulty: 2
  },
  {
    id: "comb-008",
    scope: "combinational",
    chapter: "组合逻辑",
    title: "组合逻辑设计步骤",
    type: "analysis",
    text: "请简述设计一个组合逻辑电路的一般步骤，并举例说明它可用于编码器、译码器、数据选择器、加法器或比较器。",
    options: [],
    answerText: "一般步骤为：明确输入输出变量，列真值表，写出逻辑表达式，化简表达式，选择门电路或集成器件实现，最后验证功能。可用于全加器、译码器、比较器等组合逻辑设计。",
    explanation: "组合逻辑电路没有记忆功能，输出只由当前输入决定，因此真值表和逻辑函数化简是核心步骤。",
    knowledge: ["组合逻辑设计", "编码器", "译码器", "数据选择器", "加法器", "比较器"],
    keywords: ["真值表", "化简", "实现", "验证"],
    difficulty: 2
  }
].map((question) => ({
  imported: false,
  source: "平台内置题库",
  ...question
}));
